 export const ActionTypes = {
    // ACTIONS TYPES FOR PRODUCTS
    PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",

    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",

    PRODUCT_SAVE_REQUEST: "PRODUCT_SAVE_REQUEST",
    PRODUCT_SAVE_SUCCESS: "PRODUCT_SAVE_SUCCESS",
    PRODUCT_SAVE_FAIL: "PRODUCT_SAVE_FAIL",

    PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
    PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",

    PRODUCT_REVIEW_SAVE_SUCCESS: "PRODUCT_REVIEW_SAVE_SUCCESS",
    PRODUCT_REVIEW_SAVE_REQUEST: "PRODUCT_REVIEW_SAVE_REQUEST",
    PRODUCT_REVIEW_SAVE_FAIL: "PRODUCT_REVIEW_SAVE_FAIL",
    PRODUCT_REVIEW_SAVE_RESET: "PRODUCT_REVIEW_SAVE_RESET",

    //ORDERS ACTIONS TYPES
    ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
    ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
    ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",

    ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAILS: "ORDER_DETAILS_FAILS",

    ORDER_LIST_REQUEST: "ORDER_LIST_REQUEST",
    ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
    ORDER_LIST_FAIL: "ORDER_LIST_FAIL",

    ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
    ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
    ORDER_PAY_FAIL: "ORDER_PAY_FAIL",

    ORDER_DELETE_REQUEST: "ORDER_DELETE_REQUEST",
    ORDER_DELETE_SUCCESS: "ORDER_DELETE_SUCCESS",
    ORDER_DELETE_FAIL: "ORDER_DELETE_FAIL",

    MY_ORDER_LIST_REQUEST: "MY_ORDER_LIST_REQUEST",
    MY_ORDER_LIST_SUCCESS: "MY_ORDER_LIST_SUCCESS",
    MY_ORDER_LIST_FAIL: "MY_ORDER_LIST_FAIL",

    //CART ACTION TYPES
    CART_ADD_ITEM: "CART_ADD_ITEM",
    CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
    CART_SAVE_PAYMENT: "CART_SAVE_PAYMENT",
    CART_SAVE_SHIPPING: "CART_SAVE_SHIPPING", 
 }